# Generated by Django 5.1.6 on 2025-03-07 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safetyapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='crime_location',
            new_name='location_of_crime',
        ),
    ]
