# Generated by Django 5.1.6 on 2025-03-08 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safetyapp', '0002_rename_crime_location_notification_location_of_crime'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereport',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
